kind: Pod
apiVersion: v1
metadata:
  name: testpod4
spec:
  containers:
    - name: c03
      image: httpd
      command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]
      ports:
       - containerPort: 80